### ISSUE TITLE
requestPermission crashes the app

### ISSUE THREAD

**Issue by krisidmisso** [matinzd/react-native-health-connect#19]
**Describe the bug**
`requestPermission` crashes the app after the permissions have been granted from HealthConnect screen. If the permissions are granted previously, the app crashes immediately
**To Reproduce**
1. Using the example code in this repo, trigger `requestPermission`
2. Allow all
3. Apply
4. Crash happens
Or set Allow All permissions from Health Connect settings for the app and then trigger `requestPermission`

Crash happens even if you tap on Cancel instead of Allow permission

**Expected behavior**
Crash should not happen. A permissions list should be returned by the promise
**Screenshots**

**Environment:**
 - Health Connect Version: 1.0.1
 - React Native Version: 0.69.7
 - New architecture enabled: No

Tested on 2 different real devices: 
1. S9+ with Android 10
2. S22Ultra with Android 13

**Comment by matinzd** [comment]
Can you maybe try the example app? I couldn't reproduce it there.

<img width="1209" alt="Screenshot 2023-05-08 at 18 39 51" src="https://user-images.githubusercontent.com/24797481/236880723-af4fbc8e-f442-4b24-823d-8604d8105a41.png">

**Comment by matinzd** [comment]
This [commit](https://github.com/matinzd/react-native-health-connect/commit/cef36fc448fdbe29d9413c7daaae40e9a6b791a3) may fix this issue.

**Comment by krisidmisso** [comment]
Thank you @matinzd. I double checked with the example app and it seems I dont have `newArchitechtire` enabled. I updated both my issues in this repo. 

I added the package from master, run `./gradlew clean` and run the app in android(S9+). I am still having the same issue.

I was able to get the logs at the moment of the crash:
```
2023-05-08 19:08:23.559 1195-1195/com.personal.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.personal.app, PID: 1195
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=150, result=-1, data=Intent { (has extras) }} to activity {com.personal.app/com.personal.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.auth0.android.authentication.storage.SecureCredentialsManager.checkAuthenticationResult(int, int)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.auth0.android.authentication.storage.SecureCredentialsManager.checkAuthenticationResult(int, int)' on a null object reference
        at com.auth0.react.A0Auth0Module.onActivityResult(A0Auth0Module.java:227)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:339)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:824)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:133)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
        at android.app.Activity.dispatchActivityResult(Activity.java:8300)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
2023-05-08 19:08:27.021 12499-12499/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2023-05-08 19:08:27.022 12499-12499/? E/Zygote: accessInfo : 1
2023-05-08 19:08:27.052 12499-12499/? E/com.personal.ap: Unknown bits set in runtime_flags: 0x8000
```

Hope this helps

**Comment by matinzd** [comment]
I feel that this crash is not related to this library. Are you using https://github.com/auth0/react-native-auth0?

**Comment by matinzd** [comment]
**UPDATE:**

It seems there is a coincidence. Both libraries are using the same request code for handling `onActivityResult`.

https://github.com/auth0/react-native-auth0/blob/4ff2b6e9f4f0aa3c92387f307b65d1b79a8066fb/android/src/main/java/com/auth0/react/A0Auth0Module.java#LL40C30-L40C53

**Comment by chganesh** [comment]
@matinzd added <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED"/>
    <uses-permission android:name="android.permission.health.WRITE_TOTAL_CALORIES_BURNED"/> these two permissions in android manifest but request permission getting empty 

error
-----

Possible Unhandled Promise Rejection (id: 0):
Error: [android.permission.health.WRITE_ACTIVE_CALORIES_BURNED] is not declared!
Error: [android.permission.health.WRITE_ACTIVE_CALORIES_BURNED] is not declared!

**Comment by matinzd** [comment]
@chganesh 

Based on your error, you are requesting `WRITE_ACTIVE_CALORIES_BURNED`, and have not defined it as one of your permissions. Also, please open a new issue when you have problems such as this next time.
