### ISSUE TITLE
insertRecords throws ' Error: text ' for every recordType

### ISSUE THREAD

**Issue by krisidmisso** [matinzd/react-native-health-connect#21]
**Describe the bug**
`insertRecords` throws an error for every`recortType`:

```
error insert:  Error: text
    at Object.promiseMethodWrapper [as insertRecords] (NativeModules.js:106:51)
    at insertRecords (index.tsx:131:24)
    at onPress (HealthConnectTest.js:82:24)
    at Pressability._performTransitionSideEffects (Pressability.js:756:11)
    at Pressability._receiveSignal (Pressability.js:693:12)
    at onResponderRelease (Pressability.js:524:14)
    at Object.invokeGuardedCallbackProd (ReactNativeRenderer-dev.js:107:10)
    at invokeGuardedCallback (ReactNativeRenderer-dev.js:340:31)
    at invokeGuardedCallbackAndCatchFirstError (ReactNativeRenderer-dev.js:364:25)
    at executeDispatch (ReactNativeRenderer-dev.js:466:3)
```

**To Reproduce**
After initialization, trigger below code:
```
insertRecords([
        {
          recordType: 'Hydration',
          volume: {unit: 'milliliters', value: 250},
        },
      ])
        .then(value => console.log(value))
        .catch(e => console.log('error insert: ', e));
```

**Expected behavior**
Record should be added and then retrieved successfully

**Environment:**
 - Health Connect Version: 1.0.2
 - React Native Version: 0.69.7
 - New architecture enabled: No

**Comment by krisidmisso** [comment]
Adding `startTime` and `endTime` the error  doesnt appear anymore for some of the recordTypes (Steps, Hydration, Calories) but it appears for Height and Weight

**Comment by matinzd** [comment]
You always need to provide `startTime` and `endTime` or `time` based on the type of record.
