### ISSUE TITLE
Error: Unable to resolve module when running metro on example app

### ISSUE THREAD

**Issue by micnem** [matinzd/react-native-health-connect#64]
Description: 
When trying to run the example app, it builds fine but Metro crashes with the following error:
```
error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/michaeln/Desktop/react-native-health-connect/src/errors.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project.
> 1 | export class HealthConnectError extends Error {
    | ^
  2 |   constructor(message: string, method: string) {
  3 |     super(`HealthConnect.${method}: ${message}`);
  4 |   }
    at ModuleResolver.resolveDependency (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:150:15)
    at DependencyGraph.resolveDependency (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/node-haste/DependencyGraph.js:282:43)
    at Object.resolve (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/lib/transformHelpers.js:176:21)
    at Graph._resolveDependencies (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/DeltaBundler/Graph.js:476:35)
    at Graph._processModule (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 3)
    at async Graph._processModule (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/Users/michaeln/Desktop/react-native-health-connect/example/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 5)
```
1. run `npm start` in `react-native-health-connect/example`

Screenshot from device:
![Screenshot_20240211-184712_React Health Connect](https://github.com/matinzd/react-native-health-connect/assets/29963598/56556ae7-685e-4a63-accc-cc16d0e84a9a)

**Environment:**
 - Health Connect Version:`1.1.0-alpha06`
 - React Native Version: `0.73.1`
 - New architecture enabled: No

**Comment by matinzd** [comment]
What node version are you using?

**Comment by matinzd** [comment]
You are using the old version of the library from 1 year ago. Please update to the latest version and see if the issue still exists.

**Comment by matinzd** [comment]
Closing this due to inactivity.
